### ISSUE TITLE
‘benchmark’ and ‘status’ option similar to steam-prefill

### ISSUE THREAD

**Issue by nazgul6** [tpill90/epic-lancache-prefill#60]
Hi. Not an issue, but a question on whether feature parity with steam-prefill is possible to be added? 

Thanks!

**Comment by tpill90** [comment]
From a technical standpoint it's absolutely possible. It would mostly be copy and pasting the appropriate code and swapping out the steam specific things for it's epic equivalent. 

Realistically speaking it's really a matter of the time investment for the payoff here.  SteamPrefill is the most used out of the prefills by a long shot, and EpicPrefill is the least used one.  Since the SteamPrefill feature already covers the same use case I don't see myself investing time into porting it over, not at least while I have other things I could invest the time into first. 

That said I have no issues merging this change in if you were to implement it. I'd gladly help walk you through where the changes need to be made as well.

**Comment by tpill90** [comment]
Closing this as I don't currently plan to implement this.  I will however gladly merge in these changes for anyone who is interested in implementing them.

**Comment by tpill90** [comment]
Closing this as I don't currently plan to implement this.  I will however gladly merge in these changes for anyone who is interested in implementing them.
